### ISSUE TITLE
List index out of range error

### ISSUE THREAD

**Issue by egh** [PLOS/allofplos#121]
Running the following code:
```python
from allofplos import Corpus
corpus = Corpus()
for article in corpus[:10]:
  str(article)
```

raises the error:
```
10.1371/journal.pbio.0000003 Traceback (most recent call last):
  File "x.py", line 4, in <module>
    print(article.doi, article)
  File "/home/egh/.virtualenvs/allofplos/lib/python3.6/site-packages/allofplos/article_class.py", line 126, in __str__
    root.remove(back[0])
IndexError: list index out of range
```

**Comment by egh** [comment]
Possibly related to #120

**Comment by egh** [comment]
Seems to be working after #122 was merged.
